[build]
  base    = "enzo-reports/frontend"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from   = "/api-jbi/*"
  to     = "https://backend-greymix-jbi.bis-apps.com/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/api-shifer/*"
  to     = "https://backend-greymix.bis-apps.com/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/api/*"
  to     = "https://backend-greymix-sement.bis-apps.com/api/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
